export const doctorateOptions = [
  "Ph.D/Doctorate",
  "MPHIL",
  "Other Doctorate"
];

export const mastersOptions = [
  "MBA/PGDM",
  "M.Tech",
  "MS/M.Sc(Science)",
  "MCA",
  "M.Com",
  "PG Diploma",
  "M.A",
  "CA",
  "CS",
  "DM",
  "ICWA (CMA)",
  "Integrated PG",
  "LLM",
  "M.Arch",
  "M.Ch",
  "M.Des.",
  "M.Ed",
  "M.Pharma",
  "MCM",
  "MDS",
  "Medical-MS/MD",
  "MFA",
  "MVSC",
  "Post Graduate Diploma in Information Technology",
  "Master in IT Management",
  "Master of Business Administration in International Business",
  "Post Graduate Diploma in International Business",
  "Master of Science in International Business",
  "Post Graduate Diploma in Mass Communication",
  "Master of Arts in Mass Communication",
  "Master of Journalism and Mass Communication",
  "Master of Science in Biomedical Science",
  "Master of Science in Medical Microbiology",
  "Master of Science in Medical Laboratory Science",
  "Master of Science in Marketing",
  "Post Graduate Diploma in Marketing Management",
  "Master of Science in Nursing and Master of Business Administration",
  "Post Graduate Diploma in Nursing Education",
  "Master of Public Administration",
  "Master of Political Science",
  "Master of Public Policy",
  "Master of Arts in Media and Communication",
  "Post Graduate Diploma in Journalism and Mass Communication",
  "Master of Arts in Journalism and Mass Communication",
  "Master of Science in Human Resource Management",
  "Master of Human Resource Development",
  "Master of Human Resources and Industrial Relation",
  "Diplomate National Board (DNB)",
  "Diploma",
  "Diplomate of National Board (DNB)",
  "DM (Doctor of Medicine)",
  "Fellowship",
  "Other Post Graduate"
];

export const mastersCommonOptions = [
  "CA",
  "CS",
  "Integrated PG",
  "M.A",
  "M.Com",
  "MS/M.Sc(Science)",
  "M.Tech",
  "MBA/PGDM",
  "MCA",
  "PG Diploma"
];

export const graduationOptions = [
  "B.Tech/B.E.", 
  "B.Com", 
  "B.Sc", 
  "B.A", 
  "Diploma", 
  "B.Arch", 
  "B.B.A/ B.M.S", 
  "B.Des.", 
  "B.Ed", 
  "B.El.Ed", 
  "B.P.Ed", 
  "B.Pharma", 
  "B.U.M.S", 
  "BAMS", 
  "BCA", 
  "BDS", 
  "BFA", 
  "BHM", 
  "BHMCT", 
  "BHMS", 
  "BVSC", 
  "LLB", 
  "MBBS", 
  "Diploma in Elementary Education", 
  "Junior Basic Training", 
  "BS", 
  "Bachelor of Liberal Arts", 
  "Bachelor of Music", 
  "Bachelor of Public Health", 
  "Bachelor of Urban Planning", 
  "Bachelor of Vocational Studies", 
  "Bachelor of Naturopathy and Yogic Sciences", 
  "Bachelor of Audiology and Speech-Language Pathology", 
  "Bachelor of Music Therapy", 
  "Company Secretary", 
  "Certified Financial Planner", 
  "Bachelor of Event Management", 
  "Bachelor of Development Studies", 
  "Bachelor of Artificial Intelligence", 
  "Bachelor of Literature", 
  "Bachelor of Social Innovation", 
  "ITI Certification", 
  "Bachelor of Commerce in Banking and Finance", 
  "Bachelor of Tourism Studies in Cultural Heritage and Eco-Tourism", 
  "Bachelor of Commerce in Business Economics", 
  "Bachelor of Science (B.Sc.) in Business Economics", 
  "Bachelor of International Economics", 
  "Bachelor of Environmental Management", 
  "Bachelor of Environmental Design", 
  "Nursery Teacher Training", 
  "B.A. Hons", 
  "Bachelor of Social Work", 
  "Bachelor of Journalism and Mass Communication", 
  "Bachelor of Physiotherapy", 
  "Bachelor of Occupational Therapy", 
  "Bachelor of Veterinary Science", 
  "B.Ed. Special Education", 
  "Other Graduate"
];

export const graduationCommonOptions = [
  "B.A", 
  "BCA", 
  "B.B.A/ B.M.S", 
  "B.Com", 
  "B.Ed", 
  "B.Pharma", 
  "B.Sc", 
  "B.Tech/B.E.", 
  "LLB", 
  "Diploma"
];

export const educationBoardOptions = [
  "CBSE", 
  "CISCE(ICSE/ISC)", 
  "Diploma", 
  "National Open School", 
  "IB(International Baccalaureate)", 
  "-----State Boards-----", 
  "Andhra Pradesh", 
  "Arunachal Pradesh", 
  "Assam", 
  "Bihar", 
  "Chhattisgarh", 
  "Goa", 
  "Gujarat", 
  "Haryana", 
  "Himachal Pradesh", 
  "J & K", 
  "Jharkhand", 
  "Karnataka", 
  "Kerala", 
  "Madhya Pradesh", 
  "Maharashtra", 
  "Manipur", 
  "Meghalaya", 
  "Mizoram", 
  "Nagaland", 
  "Odisha", 
  "Punjab", 
  "Rajasthan", 
  "Tamil Nadu", 
  "Telangana", 
  "Tripura", 
  "Uttar Pradesh", 
  "Uttarakhand", 
  "West Bengal", 
  "Other"
];

export const educationBoardCommonOptions = [
  "CBSE", 
  "CISCE(ICSE/ISC)", 
  "Diploma", 
  "National Open School", 
  "IB(International Baccalaureate)"
];

export const mediumOptions = [
  "Assamese / Asomiya",
  "Bengali / Bangla",
  "English",
  "Gujarati",
  "Hindi",
  "Kannada",
  "Kashmiri",
  "Konkani",
  "Malayalam",
  "Manipuri",
  "Marathi",
  "Oriya",
  "Punjabi",
  "Sanskrit",
  "Tamil",
  "Telugu",
  "Urdu",
  "Other"
];

export const percentageOptions = [
  "< 40%",
  "40-44.9%",
  "45-49.9%",
  "50-54.9%",
  "55-59.9%",
  "60-64.9%",
  "65-69.9%",
  "70-74.9%",
  "75-79.9%",
  "80-84.9%",
  "85-89.9%",
  "90-94.9%",
  "95-99.9%",
  "100%"
];

export const designationOptions = [
  "HR",
  "Founder",
  "Talent Acquisition"
];

export const companySizeOptions = [
  "1-10",
  "10-50",
  "50-200",
  "200+"
];

export const industryOptions = [
  "Information Technology",
  "Healthcare",
  "Finance",
  "Education",
  "Manufacturing",
  "Retail",
  "Real Estate",
  "Transportation",
  "Telecommunications",
  "Energy",
  "Other"
];
